[[headers]]
    for = "/*"
    [headers.values]
        Referrer-Policy = "strict-origin"
        Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-XSS-Protection = "1; mode=block"
        X-Frame-Options = "DENY"

[[redirects]]
    force = true
    from = "https://leafland.nz/*"
    status = 301
    to = "https://leafland.co.nz/:splat"

[[redirects]]
    force = true
    from = "https://leafland.net.nz/*"
    status = 301
    to = "https://leafland.co.nz/:splat"

[[redirects]]
    force = true
    from = "https://leafland.org.nz/*"
    status = 301
    to = "https://leafland.co.nz/:splat"

[[redirects]]
    force = true
    from = "https://leafland.netlify.app/*"
    status = 301
    to = "https://leafland.co.nz/:splat"

[[redirects]]
    force = true
    from = "/trees/daphniphyllum-macropodum/"
    status = 301
    to = "/trees/daphniphyllum-macropodum-large-stalked-daphniphyllum/"

[[redirects]]
    force = true
    from = "/trees/prunus-mume-the-geisha-flowering-japanese-apricot/"
    status = 301
    to = "/trees/prunus-mume-the-geisha-japanese-apricot/"

[[redirects]]
    force = true
    from = "/trees/rhopalostylis-sapida-var-chathamica-nikau/"
    status = 301
    to = "/trees/rhopalostylis-sapida-var-chathamica-pitt-island-nikau-chatham-island-nikau/"

[[redirects]]
    force = true
    from = "/trees/plum-lusia/"
    status = 301
    to = "/trees/plum-luisa/"

[[redirects]]
    force = true
    from = "/trees/prunus-amanogawa-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-amanogawa-japanese-cherry/"

[[redirects]]
    force = true
    from = "/trees/prunus-kanzan-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-kanzan-japanese-cherry/"

[[redirects]]
    force = true
    from = "/trees/prunus-ichiyo-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-ichiyo-japanese-cherry/"

[[redirects]]
    force = true
    from = "/trees/prunus-shirotae-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-shirotae-japanese-cherry/"