[[headers]]
    for = "/*"
    [headers.values]
        Referrer-Policy = "strict-origin"
        Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-XSS-Protection = "1; mode=block"
        X-Frame-Options = "DENY"

[[redirects]]
    force = true
    from = "https://leafland.nz/*"
    status = 301
    to = "https://leafland.co.nz/:splat"

[[redirects]]
    force = true
    from = "https://leafland.net.nz/*"
    status = 301
    to = "https://leafland.co.nz/:splat"

[[redirects]]
    force = true
    from = "https://leafland.org.nz/*"
    status = 301
    to = "https://leafland.co.nz/:splat"

[[redirects]]
    force = true
    from = "https://leafland.netlify.app/*"
    status = 301
    to = "https://leafland.co.nz/:splat"

[[redirects]]
    force = true
    from = "/trees/daphniphyllum-macropodum/"
    status = 301
    to = "/trees/daphniphyllum-macropodum-large-stalked-daphniphyllum/"

[[redirects]]
    force = true
    from = "/trees/prunus-mume-the-geisha-flowering-japanese-apricot/"
    status = 301
    to = "/trees/prunus-mume-the-geisha-japanese-apricot/"

[[redirects]]
    force = true
    from = "/trees/rhopalostylis-sapida-var-chathamica-nikau/"
    status = 301
    to = "/trees/rhopalostylis-sapida-var-chathamica-pitt-island-nikau-chatham-island-nikau/"

[[redirects]]
    force = true
    from = "/trees/plum-lusia/"
    status = 301
    to = "/trees/plum-luisa/"

[[redirects]]
    force = true
    from = "/trees/prunus-amanogawa-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-amanogawa-japanese-cherry/"

[[redirects]]
    force = true
    from = "/trees/prunus-kanzan-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-kanzan-japanese-cherry/"

[[redirects]]
    force = true
    from = "/trees/prunus-ichiyo-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-ichiyo-japanese-cherry/"

[[redirects]]
    force = true
    from = "/trees/prunus-shirotae-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-shirotae-japanese-cherry/"

[[redirects]]
    force = true
    from = "/trees/prunus-kiku-shidare-zakura-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-kiku-shidare-zakura-japanese-cherry/"

[[redirects]]
    force = true
    from = "/trees/prunus-shimidsu-sakura-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-shimidsu-sakura-japanese-cherry/"

[[redirects]]
    force = true
    from = "/trees/prunus-tai-haku-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-tai-haku-japanese-cherry/"

[[redirects]]
    force = true
    from = "/trees/prunus-ukon-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-ukon-japanese-cherry/"

[[redirects]]
    force = true
    from = "/trees/prunus-jims-delight-flowering-cherry/"
    status = 301
    to = "/trees/prunus-campanulata-jims-delight-taiwan-cherry/"

[[redirects]]
    force = true
    from = "/trees/prunus-pink-perfection-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-pink-perfection-japanese-cherry/"

[[redirects]]
    force = true
    from = "/trees/cotinus-coggygria-grace-smoke-tree/"
    status = 301
    to = "/trees/cotinus-grace-smoke-tree/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-crimson-king-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-crimson-king-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-crimson-queen-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-crimson-queen-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-emerald-lace-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-emerald-lace-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-flavescens-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-flavescens-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-garnet-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-garnet-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-inaba-shidare-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-inaba-shidare-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-orangeola-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-orangeola-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-palmatifidum-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-palmatifidum-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-pendulum-julian-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-pendulum-julian-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-raraflora-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-raraflora-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-red-dragon-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-red-dragon-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-red-feathers-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-red-feathers-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-seiryu-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-seiryu-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-stella-rossa-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-stella-rossa-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-tamukeyama-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-tamukeyama-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-viridis-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-viridis-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/nandina-firepower/"
    status = 301
    to = "/trees/nandina-domestica-fire-power-nandina-heavenly-bamboo-sacred-bamboo/"

[[redirects]]
    force = true
    from = "/trees/acer-negundo-violaceum-box-elder/"
    status = 301
    to = "/trees/acer-negundo-var-violaceum-box-elder/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-okagami-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-o-kagami-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-omurayama-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-omure-yama-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-roseo-marginatum-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-roseomarginatum-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-var-dissectum-red-feathers-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-red-feather-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/almond-all-in-one/"
    status = 301
    to = "/trees/prunus-dulcis-all-in-one-almond/"

[[redirects]]
    force = true
    from = "/trees/almond-monovale/"
    status = 301
    to = "/trees/prunus-dulcis-monovale-almond/"

[[redirects]]
    force = true
    from = "/trees/apple-braeburn/"
    status = 301
    to = "/trees/malus-domestica-braeburn-apple/"

[[redirects]]
    force = true
    from = "/trees/apple-fuji/"
    status = 301
    to = "/trees/malus-domestica-fuji-apple/"

[[redirects]]
    force = true
    from = "/trees/apple-gala/"
    status = 301
    to = "/trees/malus-domestica-gala-apple/"

[[redirects]]
    force = true
    from = "/trees/apple-galaxy/"
    status = 301
    to = "/trees/malus-domestica-galaxy-apple/"

[[redirects]]
    force = true
    from = "/trees/apple-golden-delicious/"
    status = 301
    to = "/trees/malus-domestica-golden-delicious-apple/"

[[redirects]]
    force = true
    from = "/trees/apple-granny-smith/"
    status = 301
    to = "/trees/malus-domestica-granny-smith-apple/"

[[redirects]]
    force = true
    from = "/trees/apple-initial/"
    status = 301
    to = "/trees/malus-domestica-initial-apple/"

[[redirects]]
    force = true
    from = "/trees/apple-initial-sir-prize/"
    status = 301
    to = "/trees/malus-domestica-initial-sir-prize-apple/"

[[redirects]]
    force = true
    from = "/trees/apple-liberty/"
    status = 301
    to = "/trees/malus-domestica-liberty-apple/"

[[redirects]]
    force = true
    from = "/trees/apple-liberty-sir-prize/"
    status = 301
    to = "/trees/malus-domestica-liberty-sir-prize-apple/"

[[redirects]]
    force = true
    from = "/trees/apple-montys-surprise/"
    status = 301
    to = "/trees/malus-domestica-montys-surprise-apple/"

[[redirects]]
    force = true
    from = "/trees/apple-pacific-rose/"
    status = 301
    to = "/trees/malus-domestica-pacific-rose-apple/"

[[redirects]]
    force = true
    from = "/trees/apple-royal-gala/"
    status = 301
    to = "/trees/malus-domestica-royal-gala-apple/"

[[redirects]]
    force = true
    from = "/trees/apple-royal-gala-braeburn/"
    status = 301
    to = "/trees/malus-domestica-royal-gala-braeburn-apple/"

[[redirects]]
    force = true
    from = "/trees/apple-royal-gala-granny-smith/"
    status = 301
    to = "/trees/malus-domestica-royal-gala-granny-smith-apple/"

[[redirects]]
    force = true
    from = "/trees/apple-royal-gala-golden-delicious/"
    status = 301
    to = "/trees/malus-domestica-royal-gala-golden-delicious-apple/"

[[redirects]]
    force = true
    from = "/trees/apple-wandin-glory/"
    status = 301
    to = "/trees/malus-domestica-wandin-glory-apple/"

[[redirects]]
    force = true
    from = "/trees/apricot-royal-rosa/"
    status = 301
    to = "/trees/prunus-armeniaca-royal-rosa-apricot/"

[[redirects]]
    force = true
    from = "/trees/apricot-sundrop/"
    status = 301
    to = "/trees/prunus-armeniaca-sundrop-apricot/"

[[redirects]]
    force = true
    from = "/trees/apricot-sundrop-trevatt/"
    status = 301
    to = "/trees/prunus-armeniaca-sundrop-trevatt-apricot/"

[[redirects]]
    force = true
    from = "/trees/apricot-trevatt/"
    status = 301
    to = "/trees/prunus-armeniaca-trevatt-apricot/"

[[redirects]]
    force = true
    from = "/trees/avocado-bacon/"
    status = 301
    to = "/trees/persea-americana-bacon-avocado/"

[[redirects]]
    force = true
    from = "/trees/avocado-hass/"
    status = 301
    to = "/trees/persea-americana-hass-avocado/"

[[redirects]]
    force = true
    from = "/trees/callistemon-macarthur-bottlebrush/"
    status = 301
    to = "/trees/callistemon-viminalis-macarthur-bottlebrush/"

[[redirects]]
    force = true
    from = "/trees/callistemon-red-alert-bottlebrush/"
    status = 301
    to = "/trees/callistemon-viminalis-red-alert-bottlebrush/"

[[redirects]]
    force = true
    from = "/trees/callistemon-red-cluster-bottlebrush/"
    status = 301
    to = "/trees/callistemon-citrinus-red-cluster-bottlebrush/"

[[redirects]]
    force = true
    from = "/trees/callistemon-western-glory-bottlebrush/"
    status = 301
    to = "/trees/callistemon-citrinus-western-glory-bottlebrush/"

[[redirects]]
    force = true
    from = "/trees/camellia-ariels-song-hybrid-camellia/"
    status = 301
    to = "/trees/camellia-ariels-song-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-black-lace-hybrid-camellia/"
    status = 301
    to = "/trees/camellia-black-lace-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-cinnamon-cindy-hybrid-camellia/"
    status = 301
    to = "/trees/camellia-cinnamon-cindy-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-crimson-king-sasanqua-camellia/"
    status = 301
    to = "/trees/camellia-sasanqua-crimson-king-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-debutante-japonica-camellia/"
    status = 301
    to = "/trees/camellia-japonica-debutante-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-early-pearly-sasanqua-camellia/"
    status = 301
    to = "/trees/camellia-sasanqua-early-pearly-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-fairy-blush-hybrid-camellia/"
    status = 301
    to = "/trees/camellia-fairy-blush-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-high-fragrance-hybrid-camellia/"
    status = 301
    to = "/trees/camellia-high-fragrance-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-hiryu-sasanqua-camellia/"
    status = 301
    to = "/trees/camellia-x-vernalis-hiryu-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-jurys-yellow-hybrid-camellia/"
    status = 301
    to = "/trees/camellia-x-williamsii-jurys-yellow-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-kramers-beauty-japonica-camellia/"
    status = 301
    to = "/trees/camellia-japonica-kramers-beauty-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-kramers-supreme-japonica-camellia/"
    status = 301
    to = "/trees/camellia-japonica-kramers-supreme-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-les-jury-hybrid-camellia/"
    status = 301
    to = "/trees/camellia-x-williamsii-les-jury-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-mark-allen-hybrid-camellia/"
    status = 301
    to = "/trees/camellia-japonica-mark-alan-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-mine-no-yuki-hybrid-camellia/"
    status = 301
    to = "/trees/camellia-sasanqua-mine-no-yuki-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-nicky-crisp-hybrid-camellia/"
    status = 301
    to = "/trees/camellia-nicky-crisp-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-otome-sazanka-sasanqua-camellia/"
    status = 301
    to = "/trees/camellia-sasanqua-otome-sazanka-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-paradise-blush-sasanqua-camellia/"
    status = 301
    to = "/trees/camellia-sasanqua-paradise-blush-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-paradise-sayaka-sasanqua-camellia/"
    status = 301
    to = "/trees/camellia-sasanqua-paradise-sayaka-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-plantation-pink-sasanqua-camellia/"
    status = 301
    to = "/trees/camellia-sasanqua-plantation-pink-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-rainbow-sasanqua-camellia/"
    status = 301
    to = "/trees/camellia-sasanqua-rainbow-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-roger-hall-japonica-camellia/"
    status = 301
    to = "/trees/camellia-japonica-roger-hall-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-ruby-wedding-japonica-camellia/"
    status = 301
    to = "/trees/camellia-ruby-wedding-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-setsugekka-sasanqua-camellia/"
    status = 301
    to = "/trees/camellia-sasanqua-setsugekka-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-silver-dollar-sasanqua-camellia/"
    status = 301
    to = "/trees/camellia-sasanqua-silver-dollar-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-spring-festival-hybrid-camellia/"
    status = 301
    to = "/trees/camellia-spring-festival-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-superstar-japonica-camellia/"
    status = 301
    to = "/trees/camellia-x-williamsii-super-star-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-takanini-japonica-camellia/"
    status = 301
    to = "/trees/camellia-japonica-takanini-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-tom-knudsen-japonica-camellia/"
    status = 301
    to = "/trees/camellia-japonica-tom-knudsen-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-transnokoensis-hybrid-camellia/"
    status = 301
    to = "/trees/camellia-transnokoensis-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-transtasman-hybrid-camellia/"
    status = 301
    to = "/trees/camellia-transtasman-camellia/"

[[redirects]]
    force = true
    from = "/trees/camellia-yuletide-sasanqua-camellia/"
    status = 301
    to = "/trees/camellia-x-vernalis-yuletide-camellia/"

[[redirects]]
    force = true
    from = "/trees/cherry-compact-stella/"
    status = 301
    to = "/trees/prunus-avium-compact-stella-cherry/"

[[redirects]]
    force = true
    from = "/trees/cherry-dawson/"
    status = 301
    to = "/trees/prunus-avium-dawson-cherry/"

[[redirects]]
    force = true
    from = "/trees/cherry-lapins/"
    status = 301
    to = "/trees/prunus-avium-lapins-cherry/"

[[redirects]]
    force = true
    from = "/trees/cherry-rainier/"
    status = 301
    to = "/trees/prunus-avium-rainier-cherry/"

[[redirects]]
    force = true
    from = "/trees/cherry-stella/"
    status = 301
    to = "/trees/prunus-avium-stella-cherry/"

[[redirects]]
    force = true
    from = "/trees/cherry-summit/"
    status = 301
    to = "/trees/prunus-avium-summit-cherry/"