[[headers]]
    for = "/*"
    [headers.values]
        Referrer-Policy = "strict-origin"
        Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-XSS-Protection = "1; mode=block"
        X-Frame-Options = "DENY"

[[redirects]]
    force = true
    from = "https://leafland.nz/*"
    status = 301
    to = "https://leafland.co.nz/:splat"

[[redirects]]
    force = true
    from = "https://leafland.net.nz/*"
    status = 301
    to = "https://leafland.co.nz/:splat"

[[redirects]]
    force = true
    from = "https://leafland.org.nz/*"
    status = 301
    to = "https://leafland.co.nz/:splat"

[[redirects]]
    force = true
    from = "https://leafland.netlify.app/*"
    status = 301
    to = "https://leafland.co.nz/:splat"

[[redirects]]
    force = true
    from = "/trees/daphniphyllum-macropodum/"
    status = 301
    to = "/trees/daphniphyllum-macropodum-large-stalked-daphniphyllum/"

[[redirects]]
    force = true
    from = "/trees/prunus-mume-the-geisha-flowering-japanese-apricot/"
    status = 301
    to = "/trees/prunus-mume-the-geisha-japanese-apricot/"

[[redirects]]
    force = true
    from = "/trees/rhopalostylis-sapida-var-chathamica-nikau/"
    status = 301
    to = "/trees/rhopalostylis-sapida-var-chathamica-pitt-island-nikau-chatham-island-nikau/"

[[redirects]]
    force = true
    from = "/trees/plum-lusia/"
    status = 301
    to = "/trees/plum-luisa/"

[[redirects]]
    force = true
    from = "/trees/prunus-amanogawa-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-amanogawa-japanese-cherry/"

[[redirects]]
    force = true
    from = "/trees/prunus-kanzan-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-kanzan-japanese-cherry/"

[[redirects]]
    force = true
    from = "/trees/prunus-ichiyo-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-ichiyo-japanese-cherry/"

[[redirects]]
    force = true
    from = "/trees/prunus-shirotae-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-shirotae-japanese-cherry/"

[[redirects]]
    force = true
    from = "/trees/prunus-kiku-shidare-zakura-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-kiku-shidare-zakura-japanese-cherry/"

[[redirects]]
    force = true
    from = "/trees/prunus-shimidsu-sakura-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-shimidsu-sakura-japanese-cherry/"

[[redirects]]
    force = true
    from = "/trees/prunus-tai-haku-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-tai-haku-japanese-cherry/"

[[redirects]]
    force = true
    from = "/trees/prunus-ukon-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-ukon-japanese-cherry/"

[[redirects]]
    force = true
    from = "/trees/prunus-jims-delight-flowering-cherry/"
    status = 301
    to = "/trees/prunus-campanulata-jims-delight-taiwan-cherry/"

[[redirects]]
    force = true
    from = "/trees/prunus-pink-perfection-flowering-cherry/"
    status = 301
    to = "/trees/prunus-serrulata-pink-perfection-japanese-cherry/"

[[redirects]]
    force = true
    from = "/trees/cotinus-coggygria-grace-smoke-tree/"
    status = 301
    to = "/trees/cotinus-grace-smoke-tree/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-crimson-king-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-crimson-king-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-crimson-queen-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-crimson-queen-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-emerald-lace-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-emerald-lace-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-flavescens-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-flavescens-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-garnet-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-garnet-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-inaba-shidare-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-inaba-shidare-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-orangeola-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-orangeola-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-palmatifidum-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-palmatifidum-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-pendulum-julian-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-pendulum-julian-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-raraflora-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-raraflora-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-red-dragon-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-red-dragon-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-red-feathers-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-red-feathers-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-seiryu-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-seiryu-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-stella-rossa-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-stella-rossa-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-tamukeyama-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-tamukeyama-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-dissectum-viridis-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-var-dissectum-viridis-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/nandina-firepower/"
    status = 301
    to = "/trees/nandina-domestica-fire-power-nandina-heavenly-bamboo-sacred-bamboo/"

[[redirects]]
    force = true
    from = "/trees/acer-negundo-violaceum-box-elder/"
    status = 301
    to = "/trees/acer-negundo-var-violaceum-box-elder/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-okagami-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-o-kagami-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-omurayama-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-omure-yama-japanese-maple/"

[[redirects]]
    force = true
    from = "/trees/acer-palmatum-roseo-marginatum-japanese-maple/"
    status = 301
    to = "/trees/acer-palmatum-roseomarginatum-japanese-maple/"

