[[headers]]
    for = "/*"
    [headers.values]
        Referrer-Policy = "strict-origin"
        Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-XSS-Protection = "1; mode=block"
        X-Frame-Options = "DENY"

[[redirects]]
    force = true
    from = "https://leafland.nz/*"
    status = 301
    to = "https://leafland.co.nz/:splat"

[[redirects]]
    force = true
    from = "https://leafland.net.nz/*"
    status = 301
    to = "https://leafland.co.nz/:splat"

[[redirects]]
    force = true
    from = "https://leafland.org.nz/*"
    status = 301
    to = "https://leafland.co.nz/:splat"

[[redirects]]
    force = true
    from = "https://leafland.netlify.app/*"
    status = 301
    to = "https://leafland.co.nz/:splat"

[[redirects]]
    force = true
    from = "/trees/daphniphyllum-macropodum/"
    status = 301
    to = "/trees/daphniphyllum-macropodum-large-stalked-daphniphyllum/"